const TIPO_SOLICITUD_FACTURA = 'S';
const TIPO_FACTURA_BORRADOR = 'B';
const TIPO_FACTURA_DEFINITIVA = 'D';

module.exports = {
  TIPO_FACTURA_BORRADOR,
  TIPO_FACTURA_DEFINITIVA,
  TIPO_SOLICITUD_FACTURA
};
